host: 127.0.0.1
port: 8080
title: Language Decoder
favicon: null
dark: true
reconnect_timeout: 10
native: false   # native = True for window mode
window_size: null  # [ 1200, 1200 ]
fullscreen: false
frameless: false
reload: true
storage_secret: STORAGE_SECRET
upload:
    max_file_size: 100_000
    auto_upload: true
    max_files: 1
pdf:
    word_space: 4
    page_sep: false
    char_lim: 74
    line_lim: 54
    title_size: 24
    font_size: 13.4
    pdf_w: 215.
    pdf_h: 5.28