host: '127.0.0.1'
port: 8080
title: 'LanguageDecoder'
favicon: 'pages/ui/icon/LD-icon.png'
dark: true
debounce: 200
reconnect_timeout: 3
native: false  # native = true (window mode)
window_size: null  # [1600, 1000]
fullscreen: false  # set to false
frameless: false  # set to false
reload: true  # set to false for desktop app!!! true for dev
storage_secret: 'STORAGE_SECRET'

session_time: 10_000
on_prem: false
stream_handler: true
route_timeout: 30
files_timeout: 30

size_fct: 8.5
size_min: 50
size_max: 200
table_options: [10, 15, 20, 25, 30, 50, 0]
grid_options: [100, 150, 200, 250, 300, 'All']

api_url: 'https://openrouter.ai/api/v1'
api_key: 'c2stb3ItdjEtMjFjZDU1NTg2M2I0ZWU4Mzg0MTI4MmEwNzA4ZTk2OGFjY2RmNmQyYmEzNzRlZGJhYmQyNzUxNjRmNWMyYzI3Mw=='
model_name: 'Google: Gemini 2.0 Flash Experimental'
model_seed: 0
model_temp: 0.0
model_context: 64_000
model_age: 12  # in months

char_limit: 2850
word_limit: 1000

Upload:
    auto_upload: true
    max_files: 1

App:
    dark_mode: true
    show_tips: true
    language: 'english'
    reformatting: true
    model_name: 'Google Translator'
    http: ''
    https: ''

# A mapping dict to replace language independent characters for the source text
Replacements: {'<<': '"', '>>': '"', '«': '"', '»': '"', '"': '"', '—': '-', '–': '-'}

Pdf_params:
    pages_per_sheet: 2
    page_sep: false
    tab_size: 4
    char_lim: 75
    line_lim: 54
    top_margin: 0.3
    left_margin: -0.8
    title_size: 24
    font_size: 13.25
    title_height: 9.6
    line_height: 5.3

Regex:
    endofs: '.!?'
    puncts: '.,:;!?'
    begins: '#$§'
    ending: '°%€'
    digits: '.,:'
    opens: '<(\[{'
    close: '>)\]}'
    quotes: "\"'´`"
