host: '127.0.0.1'
port: 8080
title: 'LanguageDecoder'
favicon: 'pages/ui/icon/LD-icon.png'
dark: true
debounce: 200
reconnect_timeout: 3
native: true  # native = true (window mode)
window_size: [1600, 900]
fullscreen: false  # set to false
frameless: false  # set to false
reload: false  # set to false for production!!! true for dev
storage_secret: 'STORAGE_SECRET'

session_time: 36_000  # in seconds
on_prem: true
stream_handler: false
route_timeout: 300  # in seconds
files_timeout: 30  # in days

size_bias: 26.1
size_fct: 8.92
size_min: 50
size_max: 205
table_options: [10, 15, 20, 25, 30, 50, 0]
grid_options: [100, 150, 200, 250, 300, 'All']

api_url: 'https://openrouter.ai/api/v1'
api_key: 'c2stb3ItdjEtMjFjZDU1NTg2M2I0ZWU4Mzg0MTI4MmEwNzA4ZTk2OGFjY2RmNmQyYmEzNzRlZGJhYmQyNzUxNjRmNWMyYzI3Mw=='
model_name: 'Google: Gemini 2.0 Flash Experimental'
model_seed: 0
model_temp: 0.0
model_context: 32_000
model_age: 12  # in months

char_limit: 2_500
word_limit: 1_000

Upload:
    auto_upload: true
    max_files: 1

App:
    dark_mode: true
    show_tips: true
    language: 'english'
    reformatting: true
    model_name: 'Google Translator'
    http: ''
    https: ''

# A mapping dict to replace language independent characters for the source text
Replacements: {'<<': '"', '>>': '"', '«': '"', '»': '"', '"': '"', '—': '-', '–': '-'}

Pdf_params:
    title_size: 24
    font_size: 13.23
    top_margin: 0.4
    left_margin: -1
    char_lim: 75
    line_lim: 54
    page_lim: 2
    tab_size: 4
    page_sep: false

Regex:
    endofs: '.!?'
    puncts: '.,:;!?'
    begins: '#$§'
    ending: '°%€'
    digits: '.,:'
    opens: '<(\[{'
    close: '>)\]}'
    quotes: "\"'´`"
